version: '3.3'
services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: konex
      POSTGRES_PASSWORD: konex
      POSTGRES_DB: medicine_administration
